name: Cleanup Stale Nodes and Events

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cleanup stale files
        run: |
          CURRENT_TIMESTAMP=$(date +%s)
          
          # --- 1. Cleanup Stale Nodes ---
          STALE_NODE_SECONDS=300 # 5 minutes
          NODES_DIR="nodes"
          if [ -d "$NODES_DIR" ]; then
            find $NODES_DIR -name "*.json" | while read -r file; do
              NODE_TIMESTAMP=$(grep -o '"timestamp": [0-9]*' "$file" | sed 's/[^0-9]*//g')
              if [ -z "$NODE_TIMESTAMP" ] || [ $((CURRENT_TIMESTAMP - NODE_TIMESTAMP)) -gt $STALE_NODE_SECONDS ]; then
                echo "Removing inactive node: $file"
                git rm "$file"
              fi
            done
          fi

          # --- 2. Cleanup Expired Events ---
          EVENTS_DIR="events"
          if [ -d "$EVENTS_DIR" ]; then
            find $EVENTS_DIR -name "*.json" | while read -r file; do
              EVENT_TIMESTAMP=$(grep -o '"timestamp": [0-9]*' "$file" | sed 's/[^0-9]*//g')
              EVENT_TTL=$(grep -o '"ttl": [0-9]*' "$file" | sed 's/[^0-9]*//g')
              [ -z "$EVENT_TTL" ] && EVENT_TTL=60 # Default TTL

              if [ -z "$EVENT_TIMESTAMP" ] || [ $((CURRENT_TIMESTAMP)) -gt $((EVENT_TIMESTAMP + EVENT_TTL)) ]; then
                echo "Removing expired event: $file"
                git rm "$file"
              fi
            done
          fi

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          if ! git diff --cached --quiet; then
            git commit -m "chore: Cleanup stale nodes and events"
            git push
            echo "Cleanup complete. Changes pushed."
          else
            echo "No files to clean up."
          fi

