version: '3.8'

services:
  synapse_node:
    # Costruisce l'immagine Docker usando il Dockerfile nella directory corrente
    build: .
    # Nome del container
    container_name: synapse-node
    # Riavvia il container solo se viene fermato manualmente
    restart: unless-stopped

    # File da cui leggere le variabili d'ambiente
    env_file:
      - config.env

    # Monta i volumi per rendere persistenti i dati e fornire le credenziali
    volumes:
      # Monta la directory locale per conservare il repo clonato
      - ./synapse_state_repo:/app/synapse_state_repo
      # Monta il file delle credenziali di YouTube (sola lettura)
      - ./client_secrets.json:/app/client_secrets.json:ro
      # Monta il file del token di autenticazione per non dover ri-autorizzare ogni volta
      - ./token.pickle:/app/token.pickle
